### ISSUE TITLE
How to run MST.cu?

### ISSUE THREAD

**Issue by Michael2397** [BlackKite0206233/MSTWithCUDA#1]
There is no main function in MST.cu , how to run MST.cu? Thanks

**Comment by mhyeh** [comment]
Hi,

This is a project that I used to learn CUDA, but I started my main project
before finishing this, therefore I don't know if MST.cu can run or not.
I think MST is not difficult to implement, there also has lots of CUDA
tutorial online, maybe you can write by yourself.

Samuel Yeh

段赛赛 <notifications@github.com> 於 2018年12月22日 週六 上午11:54寫道：
